### ISSUE TITLE
不同分辨率下导出pdf样式不一样

### ISSUE THREAD

**Issue by pixiu233** [wang1xiang/html2image-pdf-word#2]
![_20231008110316](https://github.com/wang1xiang/html2image-pdf-word/assets/35750672/88b618da-50cb-4ece-bd89-07c9c04b7c0f)

**Comment by wang1xiang** [comment]
> ![_20231008110316](https://private-user-images.githubusercontent.com/35750672/273422929-88b618da-50cb-4ece-bd89-07c9c04b7c0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDkwMzksIm5iZiI6MTcwMjM0ODczOSwicGF0aCI6Ii8zNTc1MDY3Mi8yNzM0MjI5MjktODhiNjE4ZGEtNTBjYi00ZWNlLWJkODktMDdjOWMwNGI3YzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAyMzg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MmY2ZGQ1ODI2NDgxNDY4YjY3Nzk3MzUyYjFjN2I4ZjkzMTFkYmQ4MzRmMjRlN2EyNDJmYmE1YjgwZTBjNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Lymypfq0-qfkDwV177kJEB-No0NFNC8IIWcOh4kKNA)

是的，原理是截图来着，当前的缩放是什么样就截成什么样。
